version: 0.0
os: linux
files:
  - source: Website/
    destination: /home/ec2-user/Cloud_Deployment/Website/
    overwrite: true
hooks:
   BeforeInstall:
    - location: scripts/clean_destination.sh
      timeout: 300
      runas: ec2-user
