name: Terraform Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.5.7  # Specify the version of Terraform to use

      # Terraform Init
      - name: Terraform Init
        run: terraform init  # Initializes Terraform
        working-directory: ./Terraform  # Specify the directory containing Terraform files

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate  # Ensures the Terraform files are valid
        working-directory: ./Terraform

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan  # Previews changes before applying
        working-directory: ./Terraform

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve  # Automatically applies changes
        working-directory: ./Terraform
        
      # Terraform Output
      - name: Terraform Output
        run: terraform output
        working-directory: ./Terraform # Outputs the results of the Terraform apply
