name: Terraform Deployment

on:
  push:
    paths:
     - './Terraform/**'

jobs:
  terraform:
    runs-on: ubuntu-latest 

    defaults:
      run:
        working-directory: ./Terraform #every step runs in this directory that use the run command

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.4  # Specify the version of Terraform to use

      # Terraform Init that reconfigures avoiding duplicated
      - name: Terraform Init
        run: terraform init -reconfigure -input=false
        
      - name: Terraform Validate
        run: terraform validate  # Ensures the Terraform files are valid

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan  # Previews changes before applying

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -input=false -auto-approve tfplan
        
      # Terraform Output
      - name: Terraform Output
        run: terraform output # Outputs the results of the Terraform apply
