name: Terraform Deployment

on:
  push:
    branches:
      - main  # Trigger on pushes to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull requests to the main branch

jobs:
  terraform:
    runs-on: ubuntu-latest  # Runs the job on an Ubuntu runner

    steps:
      # Checkout the code
      - name: Checkout Code
        uses: actions/checkout@v2

      # Set up Terraform
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: 1.11.4  # Specify the version of Terraform to use

      # Terraform Validate
      - name: Terraform Validate
        run: terraform validate  # Ensures the Terraform files are valid

      # Terraform Init
      - name: Terraform Init
        run: terraform init  # Initializes Terraform

      # Terraform Plan
      - name: Terraform Plan
        run: terraform plan  # Previews changes before applying

      # Terraform Apply
      - name: Terraform Apply
        run: terraform apply -auto-approve  # Automatically applies changes
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      # Terraform Output
      - name: Terraform Output
        run: terraform output 
